Rewrite pkgstrap script to split repo/aur installs
AUR packages can now be specified by prefixing the line with 'aur:'.

To install only one set of packages, pass `--repo` or `--aur`.
To install *all* packages (as non-root user) pass no args or `--all`.

diff --git a/stowable/scripts/pkgstrap b/stowable/scripts/pkgstrap
--- a/stowable/scripts/pkgstrap
+++ b/stowable/scripts/pkgstrap
@@ -1,27 +1,48 @@
 #!/bin/bash
-cd packages
 
-if [ -f "$BOOTSTRAP_ROOT/.installed" ]; then
-    return
-fi
+main() {
+    local aurPackages=() repoPackages=() src="${1,,}"
 
-if [ "$OS" != "arch" ]; then
-    echo "Skipping packages, not running Arch."
-else
-    for group in *; do
-        echo "Loading packages from group $group"
-        pkglist=""
+    cd "${DOTFILES_PATH:-$HOME/.files}/packages" || exit
+    grep -q '^ID=arch$' /etc/os-release 2>/dev/null || exit
 
-        while read -r package; do
-            pkglist+=" $package"
-            echo $pkglist
-        done <<< $(grep -vE '^(\s*$|#)' "$group")
-
-        yay -S $pkglist
+    for category in *; do
+        load-packages-from "$category"
     done
-fi
 
-# Remove default zshrc ready for stow to replace our own
-rm ~/.zshrc
+    if [[ $src =~ ""|repo|--repo|all|--all ]]; then
+        echo "Installing official repo packages..."
+        [ $EUID -gt 0 ] && cmd="sudo pacman" || cmd="pacman"
+        $cmd -Syu --needed "${repoPackages[@]}"
+    fi
 
-touch "$BOOTSTRAP_ROOT/.installed"
+    if [[ $src =~ ""|aur|--aur|all|--all ]]; then
+        echo "Installing AUR packages..."
+        if [ $EUID -eq 0 ]; then
+            echo "Can't install AUR packages as root!" && exit 1
+        fi
+        yay -Syu --needed "${aurPackages[@]}"
+    fi
+}
+
+load-packages-from() {
+    echo "Parsing packages from category '$1'..."
+
+    while read -r line; do
+        if [ "${line:0:4}" == "aur:" ]; then
+            parse-aur-line "${line:4}"
+        else
+            parse-repo-line "$line"
+        fi
+    done <<< "$(grep -vE '^(\s*$|#)' "$1")"
+}
+
+parse-aur-line() {
+    for pkg in $1; do aurPackages+=("$pkg"); done
+}
+
+parse-repo-line() {
+    for pkg in $1; do repoPackages+=("$pkg"); done
+}
+
+main "$@"
